# Generated by Django 3.2.25 on 2025-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.URLField(default=2, help_text='Pega la URL de la portada del libro'),
            preserve_default=False,
        ),
    ]
