# Generated by Django 3.2.25 on 2025-06-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='cancion_destacada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
