# Generated by Django 3.2.25 on 2025-06-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publicacion_cancion_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='motivo_destacada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
