# Generated by Django 3.2.25 on 2025-06-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publicacion_motivo_destacada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='hora_creacion',
        ),
    ]
