# Generated by Django 3.2.25 on 2025-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('imagen', models.URLField(blank=True, null=True)),
                ('cancion_destacada', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_destacada', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
