# Generated by Django 3.2.25 on 2025-06-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discos',
            new_name='disco',
        ),
    ]
